const Storage = {
  TOKEN: 'LANANOTE/AUTH/TOKEN',
  DARK_MODE: 'LANANOTE/DARK_MODE',
  FIRST_LAUNCH: 'LANANOTE/FIRST_LAUNCH',
  FIRST_ONBOARDING: 'LANANOTE/FIRST_ONBOARDING',

  USER_ID: 'LANANOTE/USER_ID',
  USER_EMAIL: 'LANANOTE/USER_EMAIL',
};

export {Storage};
