const Routes = {
  UNAUTH: {
    LOGIN: 'UNAUTH/login',
    FORGOT_PASSWORD: 'UNAUTH/forgot-password',
    REGISTER: 'UNAUTH/register',
    INTRODUCTION: 'UNAUTH/introduction',
    MODAL: 'UNAUTH/MODAL',
    ONBOARDING: 'UNAUTH/ONBOARDING',
  },
  AUTH: {
    MODAL: 'AUTH/MODAL',
    ONBOARDING: 'AUTH/ONBOARDING',
    BOTTOMTAB: 'AUTH/BOTTOMTAB',
  },
  BOTTOMTAB: {
    HOME: 'BOTTOMTAB/HOME',
    INVENTORY: 'BOTTOMTAB/INVENTORY',
    INVOICE: 'BOTTOMTAB/INVOICE',
    EXPENSES: 'BOTTOMTAB/EXPENSES',
    REPORT: 'BOTTOMTAB/REPORT',
  },
  ONBOARDING: {},
  SETTINGS: {},
  OTHERS: {},
};

export {Routes};
